# Exported from Render on 2025-12-01T16:07:16Z
version: '1'
services:
  - type: web
    name: graphql-employee-data
    runtime: node
    repo: https://github.com/aynjel/graphql-employee-data
    plan: free
    envVars:
      - key: NODE_ENV
        sync: false
      - key: JWT_SECRET
        sync: false
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    buildFilter:
      paths:
        - .
